pvoutput:
  import_param: v11
  export_param: v10
public_holidays:
  country: AU
  region: NSW
tariffs:
  # precedence matters (code will check each tariff in order and stop as soon as it matches criteria)
  # off-peak is a special tariff as it is the catch-all if nothing else matches
  peak_summer:
    price: 63.6295
    start_date: 2023-11-01
    end_date: 2024-03-31
    weekdays_only: true
    times:
      - start: '14:00'
        end: '20:00'
  peak_winter:
    price: 63.6295
    start_date: 2024-06-01
    end_date: 2024-08-31
    weekdays_only: true
    times:
      - start: '17:00'
        end: '21:00'
  ev_offpeak:
    price: 7.99997
    times:
      - start: '00:00'
        end: '06:00'
  super_offpeak:
    price: 0.0
    times:
      - start: '11:00'
        end: '14:00'
  shoulder:
    price: 33.143
    times:
      - start: '07:00'
        end: '22:00'
  offpeak:
    price: 30.613
    times: []
